apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: 385551094873.dkr.ecr.eu-west-2.amazonaws.com/inventory-api:latest
        ports:
        - containerPort: 8000
